---
title: "DisGeNet Positive Class"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
symb_to_id = read_tsv("./data/symb_to_id.txt") %>%
  drop_na() 

create_positive_class <- function(dis, filename) {
  MIN_SCORE = 0.15
  
  genes = read_tsv("./data/all_gene_disease_associations.tsv") %>%
    filter(diseaseName %in% dis) %>%
    select(geneId, geneSymbol, diseaseName, diseaseId, score) %>%
    left_join(symb_to_id, by = c("geneSymbol"="gene"))
  
  positive_class = genes %>%
    filter(score >= MIN_SCORE) %>%
    drop_na() %>%
    arrange(geneId) %>%
    select(entrezID)

  write.table(positive_class, filename, row.names=FALSE, col.names=FALSE)
}
```

```{r}
create_positive_class(c("Autism Spectrum Disorders","Autistic Disorder"), "./data/autism_pos_class_labels.txt")
create_positive_class(c("Alzheimer's Disease"), "./data/alz_pos_class_labels.txt")
create_positive_class(c("Bipolar Disorder"), "./data/bipolar_pos_class_labels.txt")
create_positive_class(c("Schizophrenia"), "./data/scz_pos_class_labels.txt")
```